---
#task to Stop velocity

- name: Send shutdown command
  shell: "tmux send -t {{ byobu_velocity_tab }} ENTER 'end Server Restarting, this may take up to 30 minutes.' ENTER" 
 
- name: Wait for Shard to stop
  wait_for: "port={{ velocity_port }} state=absent timeout=300"
